### ISSUE TITLE
Version 1.0.3 is missing dist when installing a package

### ISSUE THREAD

**Issue by acbonnyac** [justinlettau/states-us#56]
## Describe the Issue

After npm installed, node_modules/states-us is missing dist directory, causing module resolution to fail when doing `import states from 'states-us';`

## Expected behavior

It should have a `dist` directory.

I think the recent change in `package.json` file that removes `npm run build` from `prepublish` step is causing this. It needs to build a `dist` directory first before publishing. Otherwise, there's no `dist` directory to be published.

**Comment by mikemunsie** [comment]
+1 Experiencing the same issue upgrading to 1.0.3. Had to force downgrade back to 1.0.2
